### ISSUE TITLE
Jobs get method not retrieving all jobs

### ISSUE THREAD

**Issue by hpooni** [pbelskiy/ujenkins#12]
The get method only seems to retrieve top layer jobs and does not seem to recurse into the folders.

**Comment by pbelskiy** [comment]
Hi! Thanks, I will check it

**Comment by pbelskiy** [comment]
@hpooni 

It's still WIP but on https://github.com/pbelskiy/ujenkins/commit/50ba86a8bfeee6ee83d04fed5004eb32dd24b629

You can use such approach:
https://github.com/pbelskiy/ujenkins#get-all-jobs-recursively

```python
def get_all_jobs(url: str = '', parent: str = '') -> Dict[str, dict]:
    jobs = {}

    for name, prop in client.jobs.get(url).items():
        jobs[parent + name] = prop
        if 'Folder' in prop.get('_class', ''):
            jobs.update(get_all_jobs(prop['url'], parent + name + '/'))

    return jobs

all_jobs = get_all_jobs()
```

Soon I will prepare patch with more functionality about getting all jobs on running Jenkins instance, and will release it.

**Comment by hpooni** [comment]
Thank you for the fast response and the interm solution. Much appreciated!

**Comment by pbelskiy** [comment]
@hpooni I've prepared second patch https://github.com/pbelskiy/ujenkins/commit/84740f783be9d28f989bf5e3fc7fd73eb3dc9089

And updated readme and examples here - https://github.com/pbelskiy/ujenkins#get-all-jobs

So, now you can use `client.jobs.get(depth=10)` to receive all jobs (actually with depth 10 which is too enough)

Any suggestions or some other things? Maybe you want some another interface here? I will release it in PyPI in a week.

**Comment by hpooni** [comment]
Thank you. That should do the trick. Currently I don't have any other use cases and it seems to be working well.

**Comment by pbelskiy** [comment]
released under https://github.com/pbelskiy/ujenkins/releases/tag/v0.9.0
