### ISSUE TITLE
Feature: getting job artifacts

### ISSUE THREAD

**Issue by robooo** [pbelskiy/ujenkins#13]
Is it possible somehow download job artifacts besides switching to aiohttp and doing downloads outside of ujenkins module?
If not would it be possible to create new function to download these artifacts, similar to getting console output?

**Comment by pbelskiy** [comment]
Hello! Thanks for feature request. So you want some interface like this?

Artefacts names could be get from builds.get_info()

```
{
  "artifacts" : [
    {
      "displayPath" : "test.txt",
      "fileName" : "test.txt",
      "relativePath" : "test.txt"
    }
  ],
}
```

```
with open('archive.tar.gz', 'wb') as f:
    content = client.builds.get_artifacts('job', 123, 'archive.tar.gz')
    f.write(content)
```

**Comment by robooo** [comment]
Thank you for the quick response! 
currently I need only that first part of getting the content from the artifact. Only one small detail if it can be `get_artifact` as we are getting only one ;)

**Comment by pbelskiy** [comment]
@robooo or it better to have same function like `builds.save_artifacts('job', 123, 'archive.tar.gz', '/tmp/local_path/')` ?

Because return binary content is not always good idea because of huge artifacts will be buffered in Python runtime which could be OOM killed by system, here better have possibility to read and save it by chunks.

**Comment by pbelskiy** [comment]
@robooo please check https://github.com/pbelskiy/ujenkins#working-with-build-artifacts

I will release it in few days.

**Comment by robooo** [comment]
Thanks for quick implementation @pbelskiy !
looking good, probably found one minor wrong comment: 
**https://github.com/pbelskiy/ujenkins/blob/master/ujenkins/endpoints/builds.py#L100**

**Comment by robooo** [comment]
Hi @pbelskiy, any new release soon?

**Comment by pbelskiy** [comment]
@robooo sorry, I will release it on this weekend!

**Comment by pbelskiy** [comment]
@robooo https://github.com/pbelskiy/ujenkins/releases/tag/v0.10.0
