### ISSUE TITLE
Bug with retries

### ISSUE THREAD

**Issue by mjste** [pbelskiy/ujenkins#15]
JenkinsClient class can have retry parameter. But passing it causes errors. I suspect it may be due to urllib3 Retry class renaming method_whitelist to allowed_methods. Renaming it locally seems to fix the problem.

ujenkins==0.10.0
urllib3==2.0.3
python3.10.7

**Comment by pbelskiy** [comment]
Hello! Thanks for bug report.

it’s probably because some other package rewrite ujenkins dependency of requests, is on new virtual env there is still same bug?

**Comment by mjste** [comment]
Yes, I tried in on new venv, installing only ujenkins. I see that in setup.py there is some code indicating that it should use urrlib3<2, but during installation `Collecting urllib3<3,>=1.21.1` was logged.

**Comment by mjste** [comment]
But now I see, that your file with setup.py (not sure, but looks relevant) was edited later that the latest version released 0.10.0 released on pypi.

**Comment by pbelskiy** [comment]
@mjste yes, you are right, please check ujenkins==0.10.1

**Comment by pbelskiy** [comment]
@mjste is it okay now?

**Comment by mjste** [comment]
Yes, I tried it with new venv, and seems fine. Thanks!
