### ISSUE TITLE
New Feature: Console Output via logText

### ISSUE THREAD

**Issue by GeneMyslinsky** [pbelskiy/ujenkins#19]
Some of my console log output is 14mb per job. I want to be able to incrementally load the console output live. 
My particular use-case, I am writing the stream to redis via a celery eventlet.

I think the feature would also be useful for running groovy scripts written locally via the api, similar to the VSCode plugin https://marketplace.visualstudio.com/items?itemName=tabeyti.jenkins-jack which I find very useful.

I was successful in replicating the same api calls one would see in the console output.

I had to create a **new endpoint** **get_output_logtext** to set a different content type and make it a POST, and I had to create a **new callback** that exposed the response headers as they are used to determine if there is more data coming, and the next index to ask for.

In the example below I use the branch to do a loop and create an async generator. I don't know how much you want to include so I tried to keep it as simple as possible.

If you are interested in this feature could you please guide me on how I should be refactoring it so that I could make the PR?

https://github.com/pbelskiy/ujenkins/commit/39c0f0e84962d9a5e8713d13dfd710bda0a232db

example:
```python
from ujenkins import AsyncJenkinsClient #this is GeneMyslinsky/ujenkins/streaming
from tm_auth.settings import settings
import nest_asyncio, asyncio
nest_asyncio.apply()

async def start_job(job_location, parameters=None):
    jenkins = AsyncJenkinsClient(settings['JENKINS_URL'], settings['JENKINS_USER'], settings['JENKINS_PASS'])
    args = {}
    if parameters: args = parameters

    queue = await jenkins.builds.start(job_location, parameters=args)
    qinfo = await jenkins.queue.get_info(queue)


    if qinfo['executable'] and qinfo['executable']['number']:
        number, url = qinfo['executable']['number'], qinfo['executable']['url']
    else:
        raise Exception("Job did not start")

    tries = 0
    while (tries := tries + 1) < 10:
        job = await jenkins.builds.get_info(job_location, number)
        if job['building']:
            break
        else:
            await asyncio.sleep(1)
    
    async for output in stream_job(job_location, number):
        print(output)
        
async def stream_job(path, number, poll_text=5):

    start = 0
    while True:
        output, headers = await jenkins.builds.get_output_logtext(path, number, start)
        yield output
        if headers.get('X-More-Data') == 'true':
            start = headers['X-Text-Size']
        else:
            break

        await asyncio.sleep(poll_text)
```

**Comment by pbelskiy** [comment]
Hello! Maybe it's easier to process polling (read chunk by chunk) outside ujenkins? And use ujenkins just to retrieve url?

But it's inconvenient because of needed to add authorisation there.
