### ISSUE TITLE
API Documentation Generation Issue

### ISSUE THREAD

**Issue by henry0312** [pbelskiy/ujenkins#20]
There is no information listed under the "API endpoints" section on [Read the Docs](https://ujenkins.readthedocs.io/en/latest/).
<img width="735" alt="image" src="https://github.com/pbelskiy/ujenkins/assets/433434/3c944bc1-cd64-4413-8495-faefe919fd96">

When I ran a Sphinx build in my local environment, the descriptions were generated as intended.
<img width="712" alt="image" src="https://github.com/pbelskiy/ujenkins/assets/433434/0ef65420-8016-4af3-b78e-e44552b47cbf">

Could it be that the build on Read the Docs is failing? 
Thank you for checking into this matter.

**Comment by pbelskiy** [comment]
@henry0312 Hi! Thanks for report! 

Yes, it's probably some misconfigured settings. I will check later, or your PR is welcome :)

**Comment by pbelskiy** [comment]
@henry0312 

But PDF looks good - https://ujenkins.readthedocs.io/_/downloads/en/stable/pdf/

**Comment by henry0312** [comment]
Thank you for fixing the issue. Your help is greatly appreciated!
