### ISSUE TITLE
CSRF Crumb Issuer Support Missing

### ISSUE THREAD

**Issue by Jaykold** [pbelskiy/ujenkins#30]
Title: CSRF Crumb Issuer Support Missing

Description:

Hi there,

I’ve been working with ujenkins and noticed that the library does not support the CSRF crumb issuer feature. This feature is crucial for Jenkins servers with CSRF protection enabled, as it prevents CSRF attacks by issuing and validating crumb tokens.

Expected Behavior:

The library should provide a mechanism to retrieve and include CSRF crumb tokens in requests to the Jenkins server.

Current Behavior:

There is no support for handling CSRF crumbs in ujenkins, which makes it challenging to interact with Jenkins servers that have CSRF protection enabled.

Steps to Reproduce:

Set up a Jenkins server with CSRF protection enabled.

Attempt to perform any operation using ujenkins without manually handling CSRF crumbs.

Observe the failure due to missing crumb tokens.

Proposed Solution:

Implement a method to fetch the CSRF crumb token from the Jenkins crumb issuer endpoint.

Include the crumb token in the headers of subsequent requests made by the library.

Additional Context:

This feature is available in other Jenkins libraries and would be a valuable addition to ujenkins.

Thank you for considering this feature request!

**Comment by pbelskiy** [comment]
Hello! Actually it has:

https://github.com/search?q=repo%3Apbelskiy%2Fujenkins%20crumb&type=code

What exactly problem do you have?

**Comment by Jaykold** [comment]
Hi there,

I initially encountered an issue while using ujenkins with a username/password to connect to Jenkins. Despite following the documentation, I couldn't create new jobs because it kept prompting for a CSRF crumb issuer. However, I recently switched to using a Jenkins token instead of a username/password, and that resolved the problem. The jobs are now being created successfully without the CSRF crumb issue.

Thank you for the prompt response and the information about the existing CSRF crumb issuer support!

**Comment by pbelskiy** [comment]
@Jaykold it also should work with username/password. Okay, so I close the issue if everything is alright now.

**Comment by Jaykold** [comment]
Yes, you can. Thanks again
