### ISSUE TITLE
Readme decode error when trying to install from source on Windows

### ISSUE THREAD

**Issue by manox** [pbelskiy/ujenkins#6]
Hi,

like I already mentioned [here](https://github.com/pbelskiy/ujenkins/issues/5#issuecomment-1151340518), when trying to install the package from source on Windows, it gives the following error.
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 738: character maps to <undefined>
```
I had to add the encoding in `setup.py` in line 18 to fix this.
```
...
with open('README.rst', encoding='utf-8') as readme_file:
...
```

**Comment by pbelskiy** [comment]
Fixed here https://github.com/pbelskiy/ujenkins/commit/f01eddd81a17f48af016674de109e2e555d6c524

Please check

PS: You could create PR for this next time :-)

**Comment by manox** [comment]
Works. Sorry, that was a combination of laziness and not much experience with Github. Will be done next time.
